import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";

// One-time Temu catalog import (50 trending fitness products). Delete after use.
const SECRET = "vlr-temu-50-x7k2m9q4w8z1n5p3";
const MERCHANT = { slug: "temu", name: "Temu", website: "https://www.temu.com" };

const PRODUCTS = [
    {
      key: "temu-adj-dumbbell-55",
      name: "55 Lbs Adjustable Dumbbells Pair - 5 in 1 Quick Adjusting Set for Home Gym",
      price: 168.38,
      reviews: 169,
      image: "https://img.kwcdn.com/product/fancy/a73c4008-13cf-4b2e-8786-466142f8eb0c.jpg",
      aff: "https://temu.to/k/pd7kpxx86gf",
      cat: "men-strength-training",
      gender: "MEN",
    },
    {
      key: "temu-costoffs-15in1",
      name: "Costoffs 15-in-1 Quick-Adjust Dumbbell 5LBS-52.5LBS, Space-Saving",
      price: 115.99,
      reviews: 40,
      image: "https://img.kwcdn.com/local-goods-image/217a7c6468/83dff4e4-30a1-44ce-ae35-7961b2495b3b_1000x1000.jpeg",
      aff: "https://temu.to/k/pi1ve8jx9e0",
      cat: "men-strength-training",
      gender: "MEN",
    },
    {
      key: "temu-caphaus-kettlebell",
      name: "CAPHAUS Cast Iron Kettlebells 10-80 LBS for Strength Training & Crossfit",
      price: 46.45,
      reviews: 352,
      image: "https://img.kwcdn.com/local-goods-image/1fee580000/5724309b-c5b2-4073-b150-972840f71251_2200x2200.jpeg",
      aff: "https://temu.to/k/p093nhoay1y",
      cat: "strength-training",
      gender: "WOMEN",
    },
    {
      key: "temu-dumbbell-55pair",
      name: "55LB Adjustable Dumbbells Pair with Tray, 5-in-1 Free Weight Set",
      price: 168.38,
      reviews: 60,
      image: "https://img.kwcdn.com/product/fancy/4a5c9696-ef79-41a5-ae94-e1c88f0a8a1c.jpg",
      aff: "https://temu.to/k/p8ybujy3k4d",
      cat: "men-strength-training",
      gender: "MEN",
    },
    {
      key: "temu-costoffs-spinlock",
      name: "Costoffs Adjustable Dumbbells Set 33-66LBS with Spinlock Collars, Home Gym",
      price: 36.55,
      reviews: 20,
      image: "https://img.kwcdn.com/local-goods-image/21f0662f80/f24e51ee-8e30-444c-8091-bd43ff810fc1_1000x1000.jpeg",
      aff: "https://temu.to/k/p4nle3ca346",
      cat: "men-strength-training",
      gender: "MEN",
    },
    {
      key: "temu-dumbbell-2550",
      name: "25/50 Lbs Adjustable Dumbbell Set with Tray, Fast Adjust, Home Gym",
      price: 97.85,
      reviews: 23,
      image: "https://img.kwcdn.com/product/fancy/82d09e02-85f6-42c9-8f7a-c37c7c00688e.jpg",
      aff: "https://temu.to/k/p54zoum9zc7",
      cat: "strength-training",
      gender: "WOMEN",
    },
    {
      key: "temu-eisenlink-plates",
      name: "Eisenlink Adjustable Dumbbell Plates 5lb x6 with Quick-Lock, up to 160lbs",
      price: 46.74,
      reviews: 114,
      image: "https://img.kwcdn.com/product/fancy/6ef8896b-c6a2-450f-97c9-420169c11d88.jpg",
      aff: "https://temu.to/k/p30b12fcwqf",
      cat: "men-strength-training",
      gender: "MEN",
    },
    {
      key: "temu-dumbbell-barbell",
      name: "Convertible Dumbbell to Barbell Set 20-80lbs Adjustable, Full-Body Workout",
      price: 27.73,
      reviews: 62,
      image: "https://img.kwcdn.com/product/fancy/c3f9a065-f658-40fd-b7a3-d039048a66f8.jpg",
      aff: "https://temu.to/k/pouq5pk63y6",
      cat: "men-workout-equipment",
      gender: "MEN",
    },
    {
      key: "temu-dumbbell-10in1",
      name: "10-in-1 Quick Adjust Dumbbell Set 25-90LBS with Tray, Anti-Slip Handle",
      price: 164.04,
      reviews: 7,
      image: "https://img.kwcdn.com/product/fancy/5171d39e-2e41-49a9-8974-8e4c6b503c3e.jpg",
      aff: "https://temu.to/k/px6rb4dui84",
      cat: "men-strength-training",
      gender: "MEN",
    },
    {
      key: "temu-dumbbell-70lbs",
      name: "70Lbs Adjustable Dumbbell & Barbell Set 4-in-1 with Connecting Rod",
      price: 60.79,
      reviews: 44,
      image: "https://img.kwcdn.com/product/fancy/f9bea728-7b3d-4cc6-aa9d-6f50a2b8f72b.jpg",
      aff: "https://temu.to/k/pxe2mpiag08",
      cat: "strength-training",
      gender: "WOMEN",
    },
    {
      key: "temu-barbell-1inch",
      name: "1-Inch Standard Barbell, 300 LB Capacity Steel Bar for Home Workouts",
      price: 27.6,
      reviews: 227,
      image: "https://img.kwcdn.com/local-goods-image/201365d0000/a2821670-3ae9-4871-9876-b79f1bf618a3_1162x1162.jpeg",
      aff: "https://temu.to/k/pp9wq503mr8",
      cat: "men-workout-equipment",
      gender: "MEN",
    },
    {
      key: "temu-barbell-collars",
      name: "Olympic Barbell Collars Pair, Quick-Release Safety Clips for Heavy Lifting",
      price: 9.07,
      reviews: 129,
      image: "https://img.kwcdn.com/product/fancy/9ee3f4b7-332c-40ab-b642-2d693bb06d19.jpg",
      aff: "https://temu.to/k/pprzinynujy",
      cat: "men-fitness-accessories",
      gender: "MEN",
    },
    {
      key: "temu-vevor-trapbar",
      name: "VEVOR Trap Bar Hex Bar, 800 LBS Capacity for Squats & Deadlifts",
      price: 153.73,
      reviews: 1,
      image: "https://img.kwcdn.com/local-goods-image/212a0c342c/11dc823c-e3e1-4e7e-b56f-2497dce375e9_1600x1600.jpeg",
      aff: "https://temu.to/k/peovj3e4nl3",
      cat: "men-workout-equipment",
      gender: "MEN",
    },
    {
      key: "temu-lifting-belt",
      name: "Weight Lifting Belt, Powerlifting Gym Belt for Fitness Training",
      price: 24.47,
      reviews: 12,
      image: "https://img.kwcdn.com/product/fancy/beed35f4-5af8-434a-a49c-d5cc29aebb2b.jpg",
      aff: "https://temu.to/k/psk0a9rfa9n",
      cat: "men-fitness-accessories",
      gender: "MEN",
    },
    {
      key: "temu-weighted-vest",
      name: "40 LB Adjustable Weighted Vest for Strength Training & Running",
      price: 46.54,
      reviews: 1116,
      image: "https://img.kwcdn.com/local-goods-image/transfer/2cfdf94a/6c4345a4-6295-4c48-9ff2-eb47c3936c5a.jpeg",
      aff: "https://temu.to/k/po4i6r7ycbr",
      cat: "men-fitness-accessories",
      gender: "MEN",
    },
    {
      key: "temu-bench-5in1",
      name: "5-in-1 Adjustable Weight Bench with Preacher Curl Pad, Foldable Home Gym",
      price: 90.59,
      reviews: 76,
      image: "https://img.kwcdn.com/product/fancy/88fbee45-ce51-459a-9c61-be52ab154c78.jpg",
      aff: "https://temu.to/k/phml8tetb3w",
      cat: "home-gym",
      gender: "WOMEN",
    },
    {
      key: "temu-bench-foldable",
      name: "Adjustable Foldable Weight Bench, Incline with Leg Rollers, 1000lb Support",
      price: 51.29,
      reviews: 64,
      image: "https://img.kwcdn.com/product/fancy/c545d309-33b6-43a6-a00e-dc45cb2989f4.jpg",
      aff: "https://temu.to/k/pyhzgc8a1h3",
      cat: "men-home-gym",
      gender: "MEN",
    },
    {
      key: "temu-power-tower",
      name: "LEASBAR Power Tower Pull Up Bar Stand, Adjustable Dip Station 330LBS",
      price: 80.71,
      reviews: 344,
      image: "https://img.kwcdn.com/product/fancy/79b31edc-2b50-425a-b588-97cbe19c4317.jpg",
      aff: "https://temu.to/k/pimowuso6wv",
      cat: "men-home-gym",
      gender: "MEN",
    },
    {
      key: "temu-dip-station",
      name: "Adjustable Power Tower Dip Station, Multi-Function Pull Up Bar for Home Gym",
      price: 59.15,
      reviews: 955,
      image: "https://img.kwcdn.com/product/fancy/c8243628-7ccc-4188-9a44-205eb6e4e848.jpg",
      aff: "https://temu.to/k/pvnxkiag0bh",
      cat: "home-gym",
      gender: "WOMEN",
    },
    {
      key: "temu-roman-chair",
      name: "Roman Chair Back Extension Machine, Hyperextension Bench, Foldable",
      price: 69.27,
      reviews: 25,
      image: "https://img.kwcdn.com/product/fancy/90c8b6a7-a991-459c-93c4-8097e46a9064.jpg",
      aff: "https://temu.to/k/p3l8tgv6ypp",
      cat: "men-home-gym",
      gender: "MEN",
    },
    {
      key: "temu-fitness-chair",
      name: "Multi-Functional Fitness Chair with Sit-Up Assistance, 800LB Capacity, Foldable",
      price: 58.98,
      reviews: 170,
      image: "https://img.kwcdn.com/product/fancy/48a2f0b3-6693-410c-b938-698aa120d974.jpg",
      aff: "https://temu.to/k/pncamqrkbsq",
      cat: "home-workouts",
      gender: "WOMEN",
    },
    {
      key: "temu-dumbbell-rack",
      name: "Four-Tier Dumbbell Rack, Multi-Layer Weight Storage Organizer for Home Gym",
      price: 56.99,
      reviews: 14,
      image: "https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/0d38125303bea78fb7a311db8ade4bc8.jpg",
      aff: "https://temu.to/k/p9et83ie4yn",
      cat: "men-home-gym",
      gender: "MEN",
    },
    {
      key: "temu-punching-ball",
      name: "Reaction Punching Ball with Suction Cup for Boxing Training & Fitness",
      price: 15.14,
      reviews: 1006,
      image: "https://img.kwcdn.com/product/fancy/0e818f9c-d5d9-4b67-9b9c-066f1c148ee3.jpg",
      aff: "https://temu.to/k/p7yf5kdg2f2",
      cat: "men-workout-equipment",
      gender: "MEN",
    },
    {
      key: "temu-ab-wheel",
      name: "Ab Wheel Roller with Knee Pads for Core Strength & Ab Workouts",
      price: 0.7,
      reviews: 448,
      image: "https://img.kwcdn.com/product/fancy/691151f6-caf0-4782-bbe6-92dc387d7e07.jpg",
      aff: "https://temu.to/k/p6nki06i6l7",
      cat: "home-workouts",
      gender: "WOMEN",
    },
    {
      key: "temu-yoga-mat-xl",
      name: "Extra Large Yoga Mat 78x54 Non-Slip Thick Mat for Yoga & Pilates",
      price: 29.98,
      reviews: 133,
      image: "https://img.kwcdn.com/product/fancy/cc26088f-51ca-43aa-afd1-e757909aa710.jpg",
      aff: "https://temu.to/k/pfjcc679k11",
      cat: "yoga",
      gender: "WOMEN",
    },
    {
      key: "temu-yoga-mat-pvc",
      name: "Non-Slip PVC Yoga Mat 3mm for Pilates, Stretching & Meditation",
      price: 13.82,
      reviews: 0,
      image: "https://img.kwcdn.com/product/open/87b163fc317e45d98312d1089f8edf5a-goods.jpeg",
      aff: "https://temu.to/k/pq2a6m0wlay",
      cat: "yoga",
      gender: "WOMEN",
    },
    {
      key: "temu-yoga-strap",
      name: "Yoga Stretch Strap Belt for Back, Hip Opening & Flexibility Training",
      price: 24.24,
      reviews: 553,
      image: "https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/63795c7955459799f112425fb530366b.jpg",
      aff: "https://temu.to/k/poh0qgk33f8",
      cat: "yoga",
      gender: "WOMEN",
    },
    {
      key: "temu-yoga-4in1",
      name: "Four-in-One Yoga Pilates Equipment Set, Stretching & Back Bend Assist",
      price: 20.7,
      reviews: 0,
      image: "https://img.kwcdn.com/product/fancy/70f80db5-b61d-40da-9c03-a9a7bf658ba5.jpg",
      aff: "https://temu.to/k/px6rcnztwkc",
      cat: "pilates",
      gender: "WOMEN",
    },
    {
      key: "temu-yoga-blocks-band",
      name: "2pcs EVA Yoga Blocks + Resistance Band Combo Set for Stretching",
      price: 7.89,
      reviews: 5,
      image: "https://img.kwcdn.com/product/fancy/f386cb80-0b27-4b8c-acbb-5eda9f41e3f5.jpg",
      aff: "https://temu.to/k/p9z7pat644t",
      cat: "yoga",
      gender: "WOMEN",
    },
    {
      key: "temu-yoga-blocks-160",
      name: "2pcs High-Density EVA Yoga Blocks, Non-Slip Waterproof for Deep Stretching",
      price: 11.38,
      reviews: 2,
      image: "https://img.kwcdn.com/product/fancy/f00a898b-580c-4918-9fb1-19372c18dcf4.jpg",
      aff: "https://temu.to/k/payca76tikx",
      cat: "pilates",
      gender: "WOMEN",
    },
    {
      key: "temu-yoga-blocks-cloud",
      name: "2 Packs Cloud-Feel Yoga Blocks, High-Density EVA Foam Non-Slip",
      price: 11.38,
      reviews: 1,
      image: "https://img.kwcdn.com/product/fancy/183a26f8-6e00-4736-b61b-e4fcc2492e72.jpg",
      aff: "https://temu.to/k/p4xt0x4px1i",
      cat: "yoga",
      gender: "WOMEN",
    },
    {
      key: "temu-aquasafe-blocks",
      name: "AQUASAFE High-Density Yoga Blocks 2pcs + Free Hook for Balance & Poses",
      price: 14.77,
      reviews: 0,
      image: "https://img.kwcdn.com/product/open/518f96a0ae9e44e38302ee9048e1427d-goods.jpeg",
      aff: "https://temu.to/k/pvzsipdte87",
      cat: "pilates",
      gender: "WOMEN",
    },
    {
      key: "temu-inversion-straps",
      name: "Yoga Inversion Straps with Door Hooks & Waist Belts for Flexibility",
      price: 18.41,
      reviews: 0,
      image: "https://img.kwcdn.com/product/fancy/5dbc5d99-cefd-4883-9ca4-df4a2b81ded3.jpg",
      aff: "https://temu.to/k/ppkqlguqkby",
      cat: "yoga",
      gender: "WOMEN",
    },
    {
      key: "temu-yoga-stick",
      name: "Adjustable Mobility Stick for Stretching, Flexibility & Balance",
      price: 24.14,
      reviews: 0,
      image: "https://img.kwcdn.com/product/fancy/59b50baa-20e2-4e90-af49-30f581faacf9.jpg",
      aff: "https://temu.to/k/pxz13kkmfps",
      cat: "mobility",
      gender: "WOMEN",
    },
    {
      key: "temu-squat-wedge",
      name: "Squat Wedge Slant Board for Calf Stretching & Ankle Mobility",
      price: 4.04,
      reviews: 469,
      image: "https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/3a404d7ba59783fcfebe4d4fa7d111e0.jpg",
      aff: "https://temu.to/k/pi2cw11icy4",
      cat: "mobility",
      gender: "WOMEN",
    },
    {
      key: "temu-calf-stretcher",
      name: "Calf Stretcher Slant Board, 3 Adjustable Angles for Ankle & Yoga",
      price: 9.52,
      reviews: 10,
      image: "https://img.kwcdn.com/product/fancy/387c2496-6fb4-4886-91c9-634828eb55c3.jpg",
      aff: "https://temu.to/k/pcpr6s5b0vr",
      cat: "mobility-tools",
      gender: "UNISEX",
    },
    {
      key: "temu-slant-board",
      name: "Wooden Slant Board, Portable Leg & Calf Stretching Tool",
      price: 9.61,
      reviews: 19,
      image: "https://img.kwcdn.com/product/fancy/cfb7f4ef-cc23-4c5f-b8b5-06e2309ca776.jpg",
      aff: "https://temu.to/k/pdrjooq8ztr",
      cat: "mobility",
      gender: "WOMEN",
    },
    {
      key: "temu-taichi-set",
      name: "3-Book Tai Chi & Chair Yoga Set for Relaxation, Wellness & Seniors",
      price: 9.3,
      reviews: 0,
      image: "https://img.kwcdn.com/product/fancy/1e37850a-72ca-4b62-943a-ac96721a0f6b.jpg",
      aff: "https://temu.to/k/pfxtwqzuz7y",
      cat: "fitness-lifestyle",
      gender: "WOMEN",
    },
    {
      key: "temu-fascia-gun",
      name: "Portable Fascia Massage Gun, 6-Speed with 8 Heads for Muscle Recovery",
      price: 1.51,
      reviews: 936,
      image: "https://img.kwcdn.com/product/fancy/c49d0e2d-7c3f-4cdb-aa8b-4401436375c3.jpg",
      aff: "https://temu.to/k/pf58u7nblkf",
      cat: "muscle-recovery",
      gender: "UNISEX",
    },
    {
      key: "temu-bands-10pcs",
      name: "10pcs Elastic Fitness Band Set for Yoga & Full Body Workout",
      price: 8.02,
      reviews: 84,
      image: "https://img.kwcdn.com/product/open/c574416c1b9b44fb9e36267f1735f359-goods.jpeg",
      aff: "https://temu.to/k/pykldegvynz",
      cat: "fitness-accessories",
      gender: "WOMEN",
    },
    {
      key: "temu-pedal-bands",
      name: "3pcs Pedal Resistance Bands with Storage Bag for Home Workout",
      price: 10.83,
      reviews: 15,
      image: "https://img.kwcdn.com/product/fancy/3d42c984-83ce-409d-adb7-410f3f311001.jpg",
      aff: "https://temu.to/k/pzwkju1bh5f",
      cat: "home-workouts",
      gender: "WOMEN",
    },
    {
      key: "temu-bands-4pcs",
      name: "4pcs Home Gym Resistance Bands for Arms, Legs & Core Training",
      price: 12.34,
      reviews: 5,
      image: "https://img.kwcdn.com/product/fancy/df60a296-8b6d-4815-83a6-37c94fb612e9.jpg",
      aff: "https://temu.to/k/p67ljmtiy5n",
      cat: "fitness-accessories",
      gender: "WOMEN",
    },
    {
      key: "temu-bands-5level",
      name: "Resistance Bands Set with 5 Levels, Professional TPE for Strength Training",
      price: 17.84,
      reviews: 10,
      image: "https://img.kwcdn.com/product/fancy/65c5b980-56b0-4f13-ad8e-d1a3dece4419.jpg",
      aff: "https://temu.to/k/p7e39t0h8av",
      cat: "men-fitness-accessories",
      gender: "MEN",
    },
    {
      key: "temu-yoga-bands",
      name: "10pcs Yoga Resistance Band Set for Legs, Hips & Thighs at Home",
      price: 11.35,
      reviews: 0,
      image: "https://img.kwcdn.com/product/open/b42268fbde384400a51b31f233b79a63-goods.jpeg",
      aff: "https://temu.to/k/p4nhtrann28",
      cat: "glute-training",
      gender: "WOMEN",
    },
    {
      key: "temu-bands-figure8",
      name: "Resistance Band Set with Figure 8 Band for Full Body Arm Back Leg Training",
      price: 13.68,
      reviews: 0,
      image: "https://img.kwcdn.com/product/fancy/f87ac6eb-b015-4e4b-9d28-d455e2b41f0e.jpg",
      aff: "https://temu.to/k/pgpzrxcz2vl",
      cat: "home-workouts",
      gender: "WOMEN",
    },
    {
      key: "temu-hip-bands",
      name: "3pcs Fabric Hip Resistance Bands for Legs, Hips & Thighs",
      price: 17.59,
      reviews: 0,
      image: "https://img.kwcdn.com/product/fancy/18e00619-a4ce-4a99-9db3-8a5643559fa9.jpg",
      aff: "https://temu.to/k/pw0b850k5zy",
      cat: "glute-training",
      gender: "WOMEN",
    },
    {
      key: "temu-pullup-bands",
      name: "LINGPENG Pull Up Resistance Bands Set with Door Anchor & Poster",
      price: 12.63,
      reviews: 0,
      image: "https://img.kwcdn.com/product/fancy/7e6459ba-3483-4772-b394-ac22071c3501.jpg",
      aff: "https://temu.to/k/pougxst9a8r",
      cat: "men-fitness-accessories",
      gender: "MEN",
    },
    {
      key: "temu-tank-top",
      name: "Women's 3pcs Lace Trim Tank Tops, Casual Sleeveless Cami Set",
      price: 8.27,
      reviews: 6,
      image: "https://img.kwcdn.com/product/Material/ImageCut/c9f9cd5c/8118bdd9-ba28-4591-adb9-c0cecf238f70.jpg",
      aff: "https://temu.to/k/pp01tdjwx3x",
      cat: "activewear",
      gender: "WOMEN",
    },
    {
      key: "temu-leggings",
      name: "Women's High-Waisted Sports Leggings, Soft Workout Yoga Pants",
      price: 9.75,
      reviews: 83,
      image: "https://img.kwcdn.com/product/temu-avi/image-crop/3e32d193-cd63-4ee3-9127-b49bc1079037.jpg",
      aff: "https://temu.to/k/p9wzrhh66yg",
      cat: "activewear",
      gender: "WOMEN",
    },
    {
      key: "temu-yoga-jacket",
      name: "Women's Yoga Half-Zip Athletic Jacket, Slim Fit Long Sleeve Top",
      price: 14.24,
      reviews: 12,
      image: "https://img.kwcdn.com/product/temu-avi/image-crop/72cf2524-9d1b-4a27-a111-9f7c1a2ddc45.jpg",
      aff: "https://temu.to/k/pu2jaghfoh4",
      cat: "activewear",
      gender: "WOMEN",
    }
];

export async function GET(req: NextRequest) {
  const key = req.nextUrl.searchParams.get("key");
  if (key !== SECRET) return NextResponse.json({ error: "unauthorized" }, { status: 401 });

  const existing = await db.product.count({ where: { slug: { in: PRODUCTS.map((p) => p.key) } } });
  if (existing > 0) {
    return NextResponse.json({ imported: false, reason: "already imported", count: existing });
  }

  const merchant = await db.merchant.upsert({
    where: { slug: MERCHANT.slug },
    update: {},
    create: { slug: MERCHANT.slug, name: MERCHANT.name, website: MERCHANT.website },
  });

  const cats = await db.category.findMany({ where: { slug: { in: Array.from(new Set(PRODUCTS.map((p) => p.cat))) } } });
  const catMap = new Map(cats.map((c) => [c.slug, c.id]));

  let created = 0;
  const skipped: string[] = [];
  for (const p of PRODUCTS) {
    const categoryId = catMap.get(p.cat);
    if (!categoryId) { skipped.push(p.key + ":no-cat"); continue; }
    try {
      await db.product.create({
        data: {
          slug: p.key,
          title: p.name,
          shortDescription: "Trending on Temu" + (p.reviews > 0 ? " - " + p.reviews + " reviews" : ""),
          price: p.price,
          currency: "USD",
          reviewCount: p.reviews > 0 ? p.reviews : null,
          rating: null,
          merchantId: merchant.id,
          affiliateUrl: p.aff,
          categoryId: categoryId,
          gender: p.gender as "WOMEN" | "MEN" | "UNISEX",
          status: "PUBLISHED",
          dataSource: "EDITORIAL",
          trendStatus: "APPROVED",
          images: { create: [{ url: p.image, alt: p.name, sortOrder: 0 }] },
          tags: { create: [{ tag: "temu" }, { tag: "trending" }] },
        },
      });
      created++;
    } catch (e: any) {
      skipped.push(p.key + ":" + String(e?.code || "err"));
    }
  }
  return NextResponse.json({ imported: true, created, skipped });
}
